// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tittkjyrkkbiiqumeeyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdHRranlya2tiaWlxdW1lZXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTMwOTYsImV4cCI6MjA2ODQ2OTA5Nn0.4L7E8hJac7gne8pYg3RB0TP1kePys7F7q5rlJyKNtNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});